service: image

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'prod'}
  timeout: 30

region: us-east-1

functions:
  image:
    handler: src/handler.image
    events:
      - stream: arn:aws:dynamodb:us-east-1:818838602878:table/podcasts/stream/2019-09-20T14:04:08.297
    environment:
      stage: ${self:provider.stage}
      IMGSERV_AWS_KEY_ID: ${ssm:IMGSERV_AWS_KEY_ID}
      IMGSERV_AWS_KEY_SECRET: ${ssm:IMGSERV_AWS_KEY_SECRET}

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  bucket:
  serverless-offline:
    port: 9000
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceExlude:
        - aws-sdk
    packager: 'npm'
    excludeFiles: src/**/*.test.ts
